---

services:
  server:
    build: .
    ports:
      - "19110:8090"
    env_file:
      - .env
    volumes:
      # - ./src:/app/src
      # - ./.env:/app/.env
      # - ./logs:/app/logs
      - /home/a/docker-data/MCP/hf-mcp-sequential-thinking:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8090/health-check || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
