---

# Run and Build 
# docker compose up -d --build
# Stop
# docker compose down

services:
  server:
    build: .
    container_name: hf-mcp-sequential-thinking
    ports:
      - "19110:8090"
    env_file:
      - .env
    volumes:
      - hf-mcp-sequential-thinking:/app
      # - /home/a/docker-data/MCP/hf-mcp-sequential-thinking:/app
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://0.0.0.0:8090/health-check || exit 1"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s

volumes:
  hf-mcp-sequential-thinking:

networks:
  hf-docker:
